# -*- coding: utf-8 -*-
"""Data Exploration -- DATA 301 Project -- Abbey Towse & Jack Rhines.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HSgYPkWcc6XVkkty7zwAKwr5KDgQf8bU

#**Data Exploration**

# Upload CSV and Import Packages
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df_football = pd.read_csv('/content/drive/MyDrive/DATA Final Project/football.csv')
df_football = df_football.drop(columns="Unnamed: 0")
df_football.head()

df_2022 = df_football[df_football["year"] == 2022]
df_football = df_football[df_football["year"] != 2022]

"""# Create Visualizations

## Scatter Plot: Overall Record and Winning Superbowl
"""

df_football["superbowl_colors"] = df_football["superbowl"].map({
    0: "black",
    1: "red"
})

df_football.plot.scatter(
    x="W-L%", y="Tm", c="superbowl_colors", alpha=0.3, title="Team Records & Super Bowl Winners"
)

# This plot looks weird with teams on Y-axis -- I flipped the axis because you couldn't read the data the other way

"""## Bar Plot: Number of Superbowl Winners based on Number of Wins"""

df_football.groupby("W")["superbowl"].sum().plot.bar(title="Super Bowl Winners by Wins")

# Potentially misleading ... how often do teams win 14 games?? (Rarely)

"""## Bar Plot: Probability of Winning the Superbowl given Number of Wins"""

joint_superbowl_wins = pd.crosstab(
    [df_football["W"]],
    df_football["superbowl"],
    normalize=True
)

joint_superbowl_wins_marginal = joint_superbowl_wins.sum(axis=1)

superbowl_given_wins = joint_superbowl_wins.divide(
    joint_superbowl_wins_marginal,
    axis=0,
)
superbowl_given_wins, superbowl_given_wins[1].plot.bar(
    title="Probability of Winning the Super Bowl Given Number of Wins"
)

"""## Bar Plot: Probability of Winning the Superbowl given Years of Experience of the Head Coach"""

joint_superbowl_years = pd.crosstab(
    [df_football["head_coach_exp_yrs"]],
    df_football["superbowl"],
    normalize=True
)

joint_superbowl_years_marginal = joint_superbowl_years.sum(axis=1)

superbowl_given_years = joint_superbowl_years.divide(
    joint_superbowl_years_marginal,
    axis=0,
)
superbowl_given_years, superbowl_given_years[1].plot.bar(
    title="Probability of Winning the Super Bowl Given Years of Head Coach Experience"
)

"""## Stacked Bar Plot: PFs, PAs, and PDs among Superbowl Winners"""

df_points = df_football[["Tm", "PF", "PA", "PD", "superbowl"]]
df_winners = df_points[df_points["superbowl"] == 1]
df_winners = df_winners.drop(columns = "superbowl")
df_winners.plot.bar(x="Tm", stacked = True, title = "PFs, PAs, and PDs among Superbowl Winners")

"""## Stacked Bar Plot: PFs, PAs, and PDs among last 5 Superbowl Winners"""

df_points = df_football[["Tm", "year", "PF", "PA", "PD", "superbowl"]]
df_winners = df_points[df_points["superbowl"] == 1]
df_winners = df_winners[df_winners["year"] > 2016]
df_winners = df_winners.drop(columns = "superbowl")
df_winners.plot.bar(x="Tm", stacked = True, title = "PFs, PAs, and PDs among last 5 Superbowl Winners")

"""## Scatter Plot: Margin of Victory vs SoS"""

df_football.plot.scatter(x="MoV", y="SoS", s=df_football["W-L%"] * 4, title = "MoV vs SoS")

"""## Box Plot: Strength of Schedule for Superbowl Winning Teams and Non-Superbowl Winning Teams"""

df_sos = df_football[["Tm", "year", "SoS", "superbowl"]]
df_winners = df_sos[df_sos["year"] > 2016]
df_winners = df_winners.drop(columns = ["year"])
df_winners = df_winners.pivot(columns = "superbowl", values="SoS")
df_winners.plot.box(title = "SoS in Superbowl Winners vs Non-Superbowl Winners")

"""## Multi Bar Plot: SRS, OSRS, and DSRS among Superbowl Winners"""

df_srs = df_football[["Tm", "SRS", "OSRS", "DSRS", "superbowl"]]
df_winners = df_srs[df_srs["superbowl"] == 1]
df_winners = df_winners.drop(columns = "superbowl")
df_winners.plot.bar(x="Tm", title = "SRS, OSRS, and DSRS Scores among Superbowl Winners")

"""## Bar Plot: Number of Superbowl Wins based on Draft Order"""

df_football.groupby("draft_order")["superbowl"].sum().plot.bar(
    title="Number of Super Bowl Wins based on Draft Order"
)

"""## Scatter Plot: Years of Experience by Head Coach and Winning the Superbowl"""

df_football.plot.scatter(
    x="head_coach_exp_yrs", y="Tm", c="superbowl_colors", alpha=0.3, title="Head Coach Experience & Super Bowl")

"""## Bar Plot: Number of Superbowl Winners based on Playoff Seed"""

df_seeds = df_football[df_football.seed != 0]

df_seeds.groupby("seed")["superbowl"].sum().plot.bar(title="Super Bowl Winners by Seed")
